apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-app
  template:
    metadata:
      labels:
        app: analytics-app
    spec:
      containers:
        - name: analytics-app
          image: 850748373480.dkr.ecr.us-east-1.amazonaws.com/analytics-app:1.0.8
          ports:
            - containerPort: 5153
          envFrom:
            - configMapRef:
                name: analytics-config
            - secretRef:
                name: analytics-secret
